version: 2.1

jobs:
  build:
    working_directory: "~/src/"
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 main.py
  test:
    working_directory: ~/src
    docker:
      - image: "circleci/python:3.6.4"
    steps:
      - checkout
      - run: python3 test_main.py

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build